### ISSUE TITLE
Joining server gives a error. (a0.1.9)

### ISSUE THREAD

**Issue by yopJJ** [oikmo/BlockBase#2]
# Joining server gives a error.
## Description

Hello @oikmo, I every time I connect to my favourite server **`afs.gurdit.com`** I seem to receive this error below. The version of the game I was using was **_[a0.1.9.](https://github.com/oikmo/BlockBase/releases/tag/a0.1.9)_**

## Crash Report
```
Generated 17/05/2024, 19:12

BlockBase a0.1.9
OS: Windows 11 (x69) version 10.0
Java: 11.0.22, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.1
[failed to get system properties (java.lang.RuntimeException: No OpenGL context found in the current thread.)]

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1510)
	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1538)
	at java.base/java.util.AbstractCollection.toArray(AbstractCollection.java:144)
	at net.oikmo.engine.world.World.update(World.java:116)
	at net.oikmo.main.Main.main(Main.java:289)
```

**Comment by oikmo** [comment]
this error shouldn't really happen often but if it occurs frequently I'll attempt to fix it.
